"""New Migration

Revision ID: bfb473eafe18
Revises: 
Create Date: 2022-05-22 19:53:43.957696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb473eafe18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('reactions_nbr', sa.Integer(), nullable=True),
    sa.Column('shares_nbr', sa.Integer(), nullable=True),
    sa.Column('comments_nbr', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('images_url', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('videos_url', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fbdata_id'), 'fbdata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fbdata_id'), table_name='fbdata')
    op.drop_table('fbdata')
    # ### end Alembic commands ###
