version: '3'

services:
  scraping:
    build: .
    command: uvicorn api.main:api --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/scraping_fb
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='wacef'
      - POSTGRES_DB='dbfbscrap'
    expose: 
      - 5432

volumes:
  postgres_data: